CREATE TABLE IF NOT EXISTS `cart`.`produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NULL DEFAULT NULL,
  `quantidade` VARCHAR(45) NULL DEFAULT NULL,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci